<a href="https://colab.research.google.com/github/masatomo-ty/power_flow_calc/blob/master/itayose.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [73]:
import numpy as np

BASE_NUM=5

Orders = np.zeros((BASE_NUM, BASE_NUM), dtype=np.float64)
print(Orders)

a1 = np.arange(0,BASE_NUM) # index [0]
a2 = np.random.uniform(1.0,8.0,BASE_NUM) # price [1]
a3 = np.random.uniform(0.5,4.0,BASE_NUM) # amount [2]
a4 = np.zeros((BASE_NUM,)) # contract amount [3]
a5 = np.stack([a1, a2, a3, a4], 1)

Node_Sellable_Rate = sorted(a5, key=lambda x: x[1])

b1 = np.arange(0,BASE_NUM)
b2 = np.random.uniform(1.0,8.0,BASE_NUM)
b3 = np.random.uniform(0.5,4.0,BASE_NUM)
b4 = np.zeros((BASE_NUM,))
b5 = np.stack([b1, b2, b3, b4], 1)

Node_Buyable_Rate = sorted(b5, reverse=True, key=lambda x: x[1])

print("=====origin=========================")
print("index, price, amount, result")
print("===============Seller===============")
print(*Node_Sellable_Rate, sep='\n')

print("===============Buyer===============")
print(*Node_Buyable_Rate, sep='\n')
print("====================================")

remain = 0
remain_b = 0
isFinal = False

for sell in Node_Sellable_Rate:
    for buy in Node_Buyable_Rate:
        if (buy[2] == 0):
            continue

        if (sell[1] <= buy[1]): # compare price
            print(round(sell[1],1), "<=", round(buy[1],1))
            if (remain == 0):
                remain = sell[2] - buy[2]
                print(remain, "=", round(sell[2],3), "-", round(buy[2],3))
            elif (remain > 0):
                remain_b = remain
                remain = remain - buy[2]
                print(remain, "=", round(remain_b,3), "-", round(buy[2],3))
            else:
                remain_b = remain
                remain = sell[2] + remain
                print(remain, "=", round(sell[2],3), "-", round(remain_b,3))
            
            if (remain >= 0):
                if remain_b >= 0:
                  print("  p1: ", int(sell[0]), "->", int(buy[0]), ": ", buy[2])
                  Orders[int(sell[0]), int(buy[0])] = buy[2]
                else:
                  print("  p2: ", int(sell[0]), "->", int(buy[0]), ": ", remain_b)
                  Orders[int(sell[0]), int(buy[0])] = - remain_b
                buy[3] = buy[2]
                buy[2] = 0
            else:
                if remain_b > 0:
                  print("  p3: ", int(sell[0]), "->", int(buy[0]), ": ", remain_b)
                  Orders[int(sell[0]), int(buy[0])] = remain_b
                else:
                  print("  p4: ", int(sell[0]), "->", int(buy[0]), ": ", sell[2])
                  Orders[int(sell[0]), int(buy[0])] = sell[2]
                sell[3] = sell[2]
                sell[2] = 0
                break
        else:
          if (not isFinal):
              isFinal = True
              if (remain >= 0):
                  sell[3] = sell[2] - remain
                  print("set sell result of ", int(sell[0]), "=", sell[3])
                  break
              else:
                  buy[3] = buy[2] + remain
                  print("set buy result of ", int(buy[0]), "=", buy[3])
                  break
              

print("====================================")
print("")
print("")
print("=====result=========================")
print("index, price, amount, result")
print("===============Seller===============")
print(*Node_Sellable_Rate, sep='\n')

print("===============Buyer===============")
print(*Node_Buyable_Rate, sep='\n')

print("===============Check Sum============")
print(np.array(Node_Buyable_Rate)[:,2].sum())
print(np.array(Node_Buyable_Rate)[:,2].sum())

print("====================================")
print(Orders)
print(Orders.sum(axis = 1))

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
=====origin=========================
index, price, amount, result
===============Seller===============
[3.         1.41955504 2.76333502 0.        ]
[1.         2.1345326  1.62134651 0.        ]
[4.         4.20077271 2.61551208 0.        ]
[0.         5.24504956 1.88319498 0.        ]
[2.         6.24309443 0.75334716 0.        ]
===============Buyer===============
[4.         6.69890938 3.64153658 0.        ]
[0.         5.89510819 3.67178371 0.        ]
[3.         4.09299878 3.512094   0.        ]
[1.         2.37699578 1.67560782 0.        ]
[2.         2.0558505  1.72199811 0.        ]
1.4 <= 6.7
-0.8782015546816875 = 2.763 - 3.642
  p4:  3 -> 4 :  2.7633350212045955
2.1 <= 6.7
0.7431449511205763 = 1.621 - -0.878
  p2:  1 -> 4 :  -0.8782015546816875
2.1 <= 5.9
-2.9286387591775735 = 0.743 - 3.672
  p3:  1 -> 0 :  0.7431449511205763
4.2 <= 5.9
-0.3131266776744339 = 2.616 - -2.929
  p4:  4 -> 

In [92]:
import numpy as np

BASE_NUM=5

Orders = np.zeros((BASE_NUM, BASE_NUM), dtype=np.float64)

for time in range(1, 5):
    np.random.seed(time)
    a1 = np.arange(0,BASE_NUM) # index [0]
    a2 = np.random.uniform(1.0,8.0,BASE_NUM) # price [1]
    a3 = np.random.uniform(0.5,4.0,BASE_NUM) # amount [2]
    a4 = np.zeros((BASE_NUM,)) # contract amount [3]
    a5 = np.stack([a1, a2, a3, a4], 1)

    Node_Sellable_Rate = sorted(a5, key=lambda x: x[1])

    b1 = np.arange(0,BASE_NUM)
    b2 = np.random.uniform(1.0,8.0,BASE_NUM)
    b3 = np.random.uniform(0.5,4.0,BASE_NUM)
    b4 = np.zeros((BASE_NUM,))
    b5 = np.stack([b1, b2, b3, b4], 1)

    Node_Buyable_Rate = sorted(b5, reverse=True, key=lambda x: x[1])

    remain = 0
    remain_b = 0
    isFinal = False

    for sell in Node_Sellable_Rate:
        for buy in Node_Buyable_Rate:
            if (buy[2] == 0):
                continue

            if (sell[1] <= buy[1]): # compare price
                if (remain == 0):
                    remain = sell[2] - buy[2]
                elif (remain > 0):
                    remain_b = remain
                    remain = remain - buy[2]
                else:
                    remain_b = remain
                    remain = sell[2] + remain
                
                if (remain >= 0):
                    if remain_b >= 0:
                      Orders[int(sell[0]), int(buy[0])] = Orders[int(sell[0]), int(buy[0])] + buy[2]
                    else:
                      Orders[int(sell[0]), int(buy[0])] = Orders[int(sell[0]), int(buy[0])] - remain_b
                    buy[3] = buy[2]
                    buy[2] = 0
                else:
                    if remain_b > 0:
                      Orders[int(sell[0]), int(buy[0])] = Orders[int(sell[0]), int(buy[0])] + remain_b
                    else:
                      Orders[int(sell[0]), int(buy[0])] = Orders[int(sell[0]), int(buy[0])] + sell[2]
                    sell[3] = sell[2]
                    sell[2] = 0
                    break
            else:
              if (not isFinal):
                  isFinal = True
                  if (remain >= 0):
                      sell[3] = sell[2] - remain
                      break
                  else:
                      buy[3] = buy[2] + remain
                      break
print(Orders)
print(Orders.T)
print(Orders.T.sum(axis = 0))
print(Orders.T/Orders.T.sum(axis = 0))

[[0.         1.65617187 2.45598931 0.         0.0473689 ]
 [2.62567112 0.         1.85299949 0.6545602  0.        ]
 [0.         0.71810826 0.         0.99135429 1.22535007]
 [2.3017436  0.95028402 0.         0.         0.68013521]
 [3.75856339 1.24245855 0.         0.         0.        ]]
[[0.         2.62567112 0.         2.3017436  3.75856339]
 [1.65617187 0.         0.71810826 0.95028402 1.24245855]
 [2.45598931 1.85299949 0.         0.         0.        ]
 [0.         0.6545602  0.99135429 0.         0.        ]
 [0.0473689  0.         1.22535007 0.68013521 0.        ]]
[4.15953009 5.13323081 2.93481262 3.93216283 5.00102194]
[[0.         0.51150459 0.         0.58536325 0.75155907]
 [0.39816322 0.         0.24468624 0.24166955 0.24844093]
 [0.59044874 0.36098114 0.         0.         0.        ]
 [0.         0.12751427 0.33779134 0.         0.        ]
 [0.01138804 0.         0.41752242 0.1729672  0.        ]]
