<a href="https://colab.research.google.com/github/masatomo-ty/power_flow_calc/blob/master/pagerank.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [15]:
import numpy as np

x = np.array([
[0, 0.5, 0.5, 0],
[0.5, 0, 0, 0.5],
[0.5, 0.5, 0, 0],
[1/3, 1/3, 1/3, 0]],
dtype=float)

M_NUM = len(x)

alpha = 0.7
G = alpha * x + (1 - alpha) * np.ones((M_NUM,M_NUM)) / M_NUM
print(G)

rank = np.array([1 for i in range(M_NUM)]) / M_NUM
print(rank)

for i in range(1000):
    rank = np.dot(rank,G)
    if i % 100 ==0:
        print(rank)

# print(np.round(rank * pagerank/rank[pagenum - 1],2))

[[0.075      0.425      0.425      0.075     ]
 [0.425      0.075      0.075      0.425     ]
 [0.425      0.425      0.075      0.075     ]
 [0.30833333 0.30833333 0.30833333 0.075     ]]
[0.25 0.25 0.25 0.25]
[0.30833333 0.30833333 0.22083333 0.1625    ]
[0.29928101 0.29928101 0.22168963 0.17974835]
[0.29928101 0.29928101 0.22168963 0.17974835]
[0.29928101 0.29928101 0.22168963 0.17974835]
[0.29928101 0.29928101 0.22168963 0.17974835]
[0.29928101 0.29928101 0.22168963 0.17974835]
[0.29928101 0.29928101 0.22168963 0.17974835]
[0.29928101 0.29928101 0.22168963 0.17974835]
[0.29928101 0.29928101 0.22168963 0.17974835]
[0.29928101 0.29928101 0.22168963 0.17974835]


In [ ]:
import numpy as np

x = np.array([
[0, 3, 1],
[2, 4, 1],
[0, 0, 9]],
dtype=float)

print(x)
print(x.T)
print(x.T.sum(axis=0))
print(x.T/x.T.sum(axis=0))

[[0. 3. 1.]
 [2. 4. 1.]
 [0. 0. 9.]]
[[0. 2. 0.]
 [3. 4. 0.]
 [1. 1. 9.]]
[4. 7. 9.]
[[0.         0.28571429 0.        ]
 [0.75       0.57142857 0.        ]
 [0.25       0.14285714 1.        ]]
